version: '3.1'
services:
  api-reservation-db:
    container_name: api-reservation-db
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_reservation'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3310:3306
